- shell:
  - command: if ! $(which brew > /dev/null); then . $DOTFILES/sh/linuxbrew.sh; fi

- brewfile:
    - brew/Basebrew
    - brew/Linuxbrew

- shell:
    - command: if $(brew --version > /dev/null); then brew update && brew upgrade; fi
