- shell:
  - command: if ! $(brew --version > /dev/null); then git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew; fi

- brewfile:
    - brew/Basebrew
    - brew/Linuxbrew

- shell:
    - command: if $(brew --version > /dev/null); then brew update && brew upgrade; fi
    - command: $(brew --prefix)/opt/fzf/install

