- shell:
    - command: if ! $(brew --version > /dev/null); then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi

- brewfile:
    - brew/Basebrew
    - brew/Osxbrew

- shell:
    - command: if $(brew --version > /dev/null); then brew update && brew upgrade; fi
