- link:
    ~/.vim: .vim
    ~/.vimrc: .vim/vimrc

- shell:
    - command: git submodule update --init --recursive .vim/pack/bundle/start/YouCompleteMe
      stdout: true
    -
      command: ./.vim/pack/bundle/start/YouCompleteMe/install.py --tern-completer
      stdout: true
