- link:
    ~/.vim: editor/vim/vim
    ~/.vimrc: editor/vim/vimrc

- shell:
    -
      command: vim +PlugClean! +PlugInstall +PlugUpdate +PlugUpgrade +qa
      stdin: true
      stdout: true
      stderr: true

