- link:
    ~/.vim: vim
    ~/.vimrc: vim/vimrc
    ~/.config/coc: vim/coc

# - shell:
#     -
#       command: vim +PlugClean! +PlugInstall +PlugUpdate! +PlugUpgrade +qa
#       stdin: true
#       stdout: true
#       stderr: true

