- link:
    '~/Library/Application Support/Code/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code/User/snippets': vscode/snippets
    '~/Library/Application Support/Code/User/keybindings.json': vscode/keybindings.json
