- defaults:
    link:
      force: true
    shell:
      stdout: true


- link:
    '~/.vscode/extensions': vscode/extensions
    '~/Library/Application Support/Code/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code/User/snippets': vscode/snippets
    '~/Library/Application Support/Code/User/keybindings.json': vscode/keybindings.json
    '~/.vscode-insiders/extensions': vscode/extensions
    '~/Library/Application Support/Code - Insiders/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code - Insiders/User/snippets': vscode/snippets
    '~/Library/Application Support/Code - Insiders/User/keybindings.json': vscode/keybindings.json

- shell:
  - defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  - defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
  - defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
  - code --install-extension vscodevim.vim
  - code --install-extension octref.vetur
  - code --install-extension kleber-swf.ocean-dark-extended
