- defaults:
    link:
      force: true

- link:
    '~/.vscode/extensions': vscode/extensions
    '~/Library/Application Support/Code/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code/User/snippets': vscode/snippets
    '~/Library/Application Support/Code/User/keybindings.json': vscode/keybindings.json
    '~/.vscode-insiders/extensions': vscode/extensions
    '~/Library/Application Support/Code - Insiders/User/settings.json': vscode/settings.json
    '~/Library/Application Support/Code - Insiders/User/snippets': vscode/snippets
    '~/Library/Application Support/Code - Insiders/User/keybindings.json': vscode/keybindings.json
