" Automatic folds (that is, folds generated by a fold method different from
" manual)
" Doc: https://github.com/Konfekt/FastFold
Plug 'Konfekt/FastFold'

nmap zuz <Plug>(FastFoldUpdate)
let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']
