- defaults:
      link:
          relink: true
          force: true
          relative: false

- clean: ['~']

- create:
      - ~/.config

- link:
      ~/.tmux: ./tmux
      ~/.tmux.conf: ./tmux/tmux.conf

      ~/.gitignore_global: ./git/gitignore_global
      ~/.gitconfig: ./git/gitconfig
      ~/.gittemplate: ./git/template

      ~/.prettierrc.js: ./.prettierrc.js
      ~/.zshenv: ./.zshenv
      ~/.ripgreprc: ./.ripgreprc
      # ~/.npmrc: ./.npmrc

      ~/.config/bat: ./.config/bat/
      ~/.config/btop: ./.config/btop/
      ~/.config/glow: ./.config/glow/
      ~/.config/lazygit: ./.config/lazygit/
      ~/.config/gh-copilot: ./.config/gh-copilot/
      ~/.config/.nuxtrc: ./.config/.nuxtrc
      ~/.config/nvim: ./.config/nvim/
      ~/.config/starship.toml: ./.config/starship.toml
      ~/.config/audio-manager: ./.config/audio-manager/
      ~/.config/yazi: ./.config/yazi/
      ~/.config/lit-test: ./.config/lit-test/

- shell:
      - [git submodule update --init, Installing submodules]
      - [command -v ya >/dev/null && ya pkg install || true, Installing yazi plugins]
