if $LINUXBREWHOME
  let g:python3_host_prog = expand("$LINUXBREWHOME/bin/python3")
endif

let g:node_host_prog = expand("$NODE_PATH/bin/neovim-node-host")
let g:coc_node_path = expand("$NODE_PATH/bin/node")

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
