" let g:python3_host_prog = expand("$LINUXBREWHOME/bin/python3.8")
let g:node_host_prog = expand("$NVM_STABLE/bin/neovim-node-host")

set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
