-- Define a hotkey to reload Hammerspoon configuration
-- hs.hotkey.bind({ "cmd", "alt" }, "R", function()
-- 	hs.reload()
-- end)
-- hs.alert.show("Config loaded")
--
-- hs.loadSpoon("AClock")
-- hs.hotkey.bind({ "cmd", "alt", "ctrl" }, "C", function()
-- 	spoon.AClock:toggleShow()
-- end)
