keybinding:
  universal:
    openDiffTool: <disabled>
customCommands:
  - key: 'N'
    context: 'localBranches'
    command: 'git-lia start'
    output: terminal
  - key: '<c-c>'
    context: 'files'
    description: 'Git lia commit'
    command: 'git-lia commit'
    output: terminal
  - key: '<c-t>'
    context: 'files'
    description: 'Git lia commit'
    command: 'lit-toggl'
    output: terminal
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  # Catppuccin Mocha theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
