keybinding:
  universal:
    openDiffTool: <disabled>
customCommands:
  - key: 'N'
    context: 'localBranches'
    command: 'git-lia start'
    output: terminal
  - key: '<c-c>'
    context: 'files'
    description: 'Git lia commit'
    command: 'git-lia commit'
    output: terminal
  - key: '<c-t>'
    context: 'files'
    description: 'Git lia commit'
    command: 'lit-toggl'
    output: terminal
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
