# Main Colors
unrecognized_file: '#94e2d5' # Teal
recognized_file: '#6c7086' # Overlay0
executable_file: '#cdd6f4' # Green
dir: '#89b4fa' # Blue

# Link
dead_link: '#f38ba8' # Red
link: '#b4befe' # Lavender

# Special Files
socket: '#a6e3a1' # Green
blockdev: '#a6e3a1' # Green
chardev: '#a6e3a1' # Green

# Access Modes
write: '#f9e2af' # Yellow
read: '#a6e3a1' # Green
exec: '#f38ba8' # Red
no_access: '#eba0ac' # Maroon

# Age
day_old: '#cba6f7' # Mauve
hour_old: '#f5c2e7' # Pink
no_modifier: '#94e2d5' # Teal

# File Size
file_large: '#f2cdcd' # Flamingo
file_medium: '#fab387' # Peach
file_small: '#f9e2af' # Yellow

# Random
report: '#bac2de' # Subtext1
user: '#a6adc8' # Subtext0
tree: '#b4befe' # Lavender
empty: '#f2cdcd' # Flamingo
error: '#f38ba8' # Red
normal: '#f9e2af' # Yellow
inode: '#9399b2' # Overlay2

# Git
addition: '#a6e3a1' # Green
modification: '#f9e2af' # Yellow
deletion: '#f38ba8' # Red
untracked: '#fab387' # Peach
unchanged: '#94e2d5' # Teal

