# Doc: https://starship.rs/config

# https://starship.rs/config/#prompt
format = """
[░▒▓](teal)\
[ $os $hostname ](fg:base bg:teal)\
[](fg:teal bg:blue)\
$directory\
[](fg:blue bg:surface2)\
$git_branch\
$git_state\
$git_status\
$custom\ 
[](fg:surface2 bg:surface1)\
$nodejs\
$php\
$docker_context\
[](fg:surface1 bg:surface0)\
$time\
[ ](fg:surface0)\
$line_break\
$character"""

scan_timeout = 30
palette = "catppuccin_mocha"
add_newline = true
command_timeout = 1500

[os]
format = "$symbol"
disabled = false

[sudo]
# format = '[$symbol](bg:#a3aed2 fg:#090c0c)'
# symbol = ""
disabled = true

[hostname]
ssh_only = true
ssh_symbol = '󰢹 '
trim_at = '.'
style = 'fg:base bg:teal'
format = '[$ssh_symbol$hostname]($style)'
disabled = false

[os.symbols]
Amazon = ""
CentOS = ""
Debian = ""
Linux = ""
Macos = ""
Raspbian = ""
Ubuntu = ""

[character]
success_symbol = "[>](bold fg:green)"
error_symbol = "[x](bold fg:red)"
vimcmd_symbol = "[V](bold fg:green)"

[directory]
style = "fg:base bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = '…/'
use_logical_path = true
read_only = '[]'

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:blue bg:surface2"
format = '[ $symbol $branch]($style)'
truncation_length = 10
truncation_symbol = '…'
only_attached = true
always_show_remote = true
# ignore_branches = ["main", "master"]

# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
# cherry_pick = '[🍒 PICKING](bold red)'

[git_status]
up_to_date = ' ✓'
style = "fg:blue bg:surface2"
stashed = '\$$count '
format = '[ $all_status$ahead_behind ]($style)'

[custom.delete_indicator]
command = """
  if git rev-parse --git-dir > /dev/null 2>&1; then
    # List branches merged into the current branch, excluding main branches
    if [ "$(git branch --merged | grep -E -v 'master|main|dev|staging|preview|production' | wc -l)" -gt 0 ]; then
      echo ""
    fi
  fi
"""
description = "Indicates if there are branches that can be deleted"
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
style = "fg:blue bg:surface2"
format = "[$output ](fg:blue bg:surface2)"

[nodejs]
symbol = ""
style = "fg:text bg:surface1"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "fg:text bg:surface1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:text bg:surface1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:text bg:surface0"
format = '[  $time ]($style)'

# https://github.com/catppuccin/starship
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
